# Практическое задание к уроку 1. Основные понятия и структуры PyTorch

In [1]:
# !pip install torch torchvision

In [2]:
import numpy as np
import torch
# import torchvision
from torch import nn #nn - формирование вычислительных графов для слоев нейронных сетей. TensorFlow: Keras
from torch import optim #optim - алгоритмы оптимизации (SGD, Adam и т.д.). TensorFlow: модуль optimizers
from torch.autograd import Variable

### 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
# вариант 1

x = torch.FloatTensor([[[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]],
                       [[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]],
                       [[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]]])
x

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]]])

In [4]:
# вариант 2

tensor = torch\
  .rand(3, 4, 5)\
  .type(torch.float32)

print(tensor)

tensor([[[0.4639, 0.3992, 0.5323, 0.9207, 0.5304],
         [0.3132, 0.8914, 0.2945, 0.5645, 0.8110],
         [0.4865, 0.8664, 0.4768, 0.7753, 0.0780],
         [0.6542, 0.0685, 0.1540, 0.8343, 0.3459]],

        [[0.3281, 0.2829, 0.5981, 0.8451, 0.7027],
         [0.8207, 0.0132, 0.5897, 0.1284, 0.8245],
         [0.3422, 0.0375, 0.4094, 0.1805, 0.2320],
         [0.1921, 0.1500, 0.2696, 0.1311, 0.4027]],

        [[0.7043, 0.6655, 0.6160, 0.3809, 0.9860],
         [0.6213, 0.7236, 0.1637, 0.6935, 0.8655],
         [0.4691, 0.6160, 0.2454, 0.3194, 0.9768],
         [0.4259, 0.8625, 0.3071, 0.2445, 0.3290]]])


### Выведите его форму (shape)

In [5]:
# вариант 1

x.shape

torch.Size([3, 4, 5])

In [6]:
# вариант 2

tensor.shape

torch.Size([3, 4, 5])

### Приведите его к форме 6 X 10

In [7]:
# вариант 1

x = x.view(-1, 10)
x

tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.]])

In [8]:
# вариант 2

print(tensor.view(6, 10))

tensor([[0.4639, 0.3992, 0.5323, 0.9207, 0.5304, 0.3132, 0.8914, 0.2945, 0.5645,
         0.8110],
        [0.4865, 0.8664, 0.4768, 0.7753, 0.0780, 0.6542, 0.0685, 0.1540, 0.8343,
         0.3459],
        [0.3281, 0.2829, 0.5981, 0.8451, 0.7027, 0.8207, 0.0132, 0.5897, 0.1284,
         0.8245],
        [0.3422, 0.0375, 0.4094, 0.1805, 0.2320, 0.1921, 0.1500, 0.2696, 0.1311,
         0.4027],
        [0.7043, 0.6655, 0.6160, 0.3809, 0.9860, 0.6213, 0.7236, 0.1637, 0.6935,
         0.8655],
        [0.4691, 0.6160, 0.2454, 0.3194, 0.9768, 0.4259, 0.8625, 0.3071, 0.2445,
         0.3290]])


### Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [9]:
# вариант 1

x * torch.FloatTensor([1, 4, 2, 2, 1, 1, 4, 2, 2, 1])

tensor([[ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.],
        [ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.],
        [ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.]])

In [10]:
# вариант 2

tensor * torch.DoubleTensor([1, 4, 2, 2, 1])

tensor([[[0.4639, 1.5969, 1.0646, 1.8414, 0.5304],
         [0.3132, 3.5657, 0.5890, 1.1289, 0.8110],
         [0.4865, 3.4658, 0.9536, 1.5505, 0.0780],
         [0.6542, 0.2739, 0.3081, 1.6686, 0.3459]],

        [[0.3281, 1.1316, 1.1963, 1.6901, 0.7027],
         [0.8207, 0.0528, 1.1793, 0.2568, 0.8245],
         [0.3422, 0.1500, 0.8187, 0.3610, 0.2320],
         [0.1921, 0.6002, 0.5392, 0.2621, 0.4027]],

        [[0.7043, 2.6621, 1.2320, 0.7619, 0.9860],
         [0.6213, 2.8944, 0.3273, 1.3870, 0.8655],
         [0.4691, 2.4641, 0.4909, 0.6388, 0.9768],
         [0.4259, 3.4501, 0.6142, 0.4891, 0.3290]]], dtype=torch.float64)

### Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [11]:
# вариант 1

torch.matmul(x, x.T)

tensor([[ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.]])

In [12]:
# вариант 2

tensor_6_10 = tensor.view(6, 10)
tensor_6_10_T = torch.transpose(tensor_6_10, 1, 0)

result = torch.matmul(tensor_6_10, tensor_6_10_T)

print(result)

tensor([[3.7427, 2.6433, 2.9179, 1.3547, 3.7752, 2.8039],
        [2.6433, 3.0939, 2.4208, 0.9783, 2.9443, 1.9056],
        [2.9179, 2.4208, 3.4711, 1.3507, 3.2211, 2.2760],
        [1.3547, 0.9783, 1.3507, 0.6839, 1.5271, 1.0269],
        [3.7752, 2.9443, 3.2211, 1.5271, 4.6021, 3.3697],
        [2.8039, 1.9056, 2.2760, 1.0269, 3.3697, 2.9036]])


### Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [13]:
# вариант 1

x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
y = x**3 + x - 75*x
y.backward(x)
print(x.grad)

tensor([ -71.0000,  -36.6250, -124.0000])


In [14]:
# вариант 2

x2 = Variable(torch.FloatTensor([1]),   requires_grad = True)
z2 = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t2 = Variable(torch.FloatTensor([2]),   requires_grad = True)

y2 = x2**3 + z2 -75*t2

y2.backward([x2, z2, t2])

(x2.grad, z2.grad, t2.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

### Создайте единичный тензор размера 5x6

In [15]:
# вариант 1

y = torch.IntTensor(np.ones([5, 6]))
y

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [16]:
# вариант 2

ones_tensor = torch.ones((5, 6))

print(ones_tensor)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


### Переведите его в формат numpy

In [17]:
# вариант 1

y.numpy()

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [18]:
# вариант 2

print(ones_tensor.numpy())

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### Возьмите функцию y = x**w1 - 2 * x**2 + 5

Посчитайте

In [19]:
# вариант 1

linear = nn.Linear(3, 3)
y = x ** linear.weight - 2 * x ** 2 + 5
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)
optimizer.zero_grad()
pred = linear(y)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  29.02969741821289


In [20]:
# вариант 2

x2 = torch.FloatTensor([1])
w1 = Variable(torch.FloatTensor([1]), requires_grad=True)

y2 = x2**w1 - 2*x2**2 + 5

In [21]:
crit = nn.MSELoss()
optimizer = optim.SGD([w1], lr=0.001)

In [22]:
w1 = nn.Linear(1, 1, bias=False)

In [23]:
optimizer.zero_grad()
x = torch.FloatTensor([5])

pred = x ** w1(torch.FloatTensor([1])) -2 * x**2 + 5
loss = criterion(pred, y)
print(loss)

tensor(2196.7109, grad_fn=<MseLossBackward0>)


/Users/alenakukhta/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([3, 3])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [24]:
loss.backward()
optimizer.step()

In [25]:
print(pred)

tensor([-44.2114], grad_fn=<AddBackward0>)


In [26]:
print(w1)
print(w1.weight.grad)

Linear(in_features=1, out_features=1, bias=False)
tensor([[-118.6955]])
